fix(precompile): add file lock when compile C++
Co-authored-by: liuhuan<liuhuan261@huawei.com>



# message auto-generated for no-merge-commit merge:
!1257 merge main_precompile into main

fix(precompile): add file lock when compile C++

Created-by: LH_123L
Commit-by: liuhuan
Merged-by: ascend-robot
Description: 修复高并发场景下重复预编译导致预编译so文件失败的问题，通过增加文件锁避免相同算子在多线程下同时访问同一个文件，
预编译报错信息：
RuntimeError: Failed to compile /tmp/tmpnaq3u8z9/launcher_cxx11abi1.cxx, error: g++:internal compiler error: Bus error signal terminated program cc1plus

The core Triton is a small number of people, and we receive many PRs (thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them.

- [ ] I am not making a trivial change, such as fixing a typo in a comment.

- [ ] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [ ] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [ ] This PR does not need a test because `FILL THIS IN`.

- Select one of the following.
  - [ ] I have not added any `lit` tests.
  - [ ] The `lit` tests I have added follow these [best practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
    including the "tests should be minimal" section. (Usually running Python code
    and using the instructions it generates is not minimal.)


See merge request: Ascend/triton-ascend!1257